language: python

python:
  - 3.6

services: postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/travisci
    - DJANGO_SETTINGS_MODULE=holdmybeer.settings.production

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - python manage.py test
