language: python

python:
  - 3.6

services: postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/travisci
    - DJANGO_SETTINGS_MODULE=holdmybeer.settings.production
    - SECRET_KEY="sekrit!!"

install:
  - pip install pipenv==11.10.0
  - pipenv install

before_script:
  - psql -c "DROP DATABASE IF EXISTS travisci;" -U postgres;
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls

